filebeat.inputs:
  # Coleta de logs do Apache
  - type: filestream
    enabled: true
    paths:
      - /usr/local/apache2/logs/access_log*
      #- /usr/local/apache2/logs/error_log*
    exclude_files: ['\.gz$']
    fields:
      log_type: apache_access_logs
    fields_under_root: true

  # Coleta de logs dos containers Docker
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
    exclude_files: ['\.gz$']
    fields:
      log_type: docker_container_logs
    fields_under_root: true

# Configuração do módulo Apache para análise de logs de acesso e erro
filebeat.modules:
  - module: apache
    access:
      enabled: true
      var.paths: ["/usr/local/apache2/logs/access_log"]
    error:
      enabled: true
      var.paths: ["/usr/local/apache2/logs/error_log"]

output.elasticsearch:
  # Definir o Elasticsearch como destino de saída
  hosts: ["http://elasticsearch:9200"]
  indices:
    - index: "apache-logs-%{+yyyy.MM.dd}"  # Índice para logs do Apache
      when.equals:
        log_type: "apache_access_logs"
    - index: "docker-logs-%{+yyyy.MM.dd}"  # Índice para logs de containers Docker
      when.equals:
        log_type: "docker_container_logs"

setup.kibana:
  # Configura o Kibana para visualização dos logs
  host: "http://kibana:5601"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

logging:
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat.log
    keepfiles: 7
    permissions: 0644
